---
- name: Set MOTD on router
  hosts: all
  gather_facts: no
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_user: admin
    ansible_password: cisco
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco
    ansible_command_timeout: 60
  tasks:
    - name: Configure MOTD
      cisco.ios.ios_config:
        lines:
          - banner motd "{{ message_from_command }}"
